FROM alpine:3.7
RUN apk update && apk add vim
ENTRYPOINT vim
#docker build -t new_image .
#run image docker run -it new_image
#check package vim if installed or not : docker exec -it $(docker ps -aq) vim
